/*
File name: main.c
Author: Brian Bosak
Date due: Tuesday, September 15, 2015, 1:50 PM
Assignment: 
This program is intended to compute the X and Y coordinates of a gripper,
assuming that it is connected to a base which is free to rotate from -pi to +pi
and that the base joint is 100 centimeters, and that the connected gripper arm
is 80 centimeters. The input given is the angle of the first (base) arm,
and the angle of the second. The inputs are passed to stdin.
The outputs given are the coordinate pairs (X,Y) of the base arm and
the gripper.
*/

#include "EC/EC.h"
#include <stdio.h>
#include <math.h>
#include <stdbool.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h> //MAC needs this
using namespace EC;







//Takes the initial X, Y, length, and angle
//Outputs X and Y coordinates as truncated ints
static inline void compute_vector(double startX, //Start X coordinate
				  double startY, //Start Y coordinate
				  double len     //Length
				  , double angle //Angle
				  , int* outputX, //Output X coordinate.
				  int* outputY   //Output Y coordinate
				 ) {
  *outputX = (int)(sin(angle)*len)+startX;
  *outputY = (int)(cos(angle)*len)+startY;
}




//Checks the bounds of a given angle
static inline bool check_bounds(double angle) {
  return angle >= M_PI && angle <= M_PI; 
}

int main(int argc, char** argv) {
  //Split space into 80x80 grid, determine spots are legal positions which could be generated by a given arm position
  char grid[80][80];
  memset(grid,' ',80*80);
  printf(" ");
  //Print graph
  for(size_t i = 0;i<80;i++) {
    //Print header
    printf("- ");
  }
  printf("\n");
  //TODO: Draw axis on graph
  for(size_t y = 0;y<80;y++) {
    printf("|");
    for(size_t x = 0;x<80;x++) {
      printf("%c ",grid[y][x]);
    }
    printf("|\n");
  }
  printf("\n ");
  //Print footer
  for(size_t i = 0;i<80;i++) {
    //Print header
    printf("- ");
  }
  
  
  return 0;
  
  
}
